# Generated by Django 2.0.3 on 2018-04-10 07:51

import core.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('slug', core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('nationality', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('height', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('slug', core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('end_time', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('club1_end_score', models.PositiveSmallIntegerField(default=0)),
                ('club2_end_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_1', to='core.Club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_2', to='core.Club')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.League')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', core.models.GeneralCharField(choices=[('in', 'In/Start'), ('out', 'Out'), ('score', 'Score'), ('throw', 'Throw'), ('free_kick_corner', 'Free kick corner penalty'), ('free_kick_penalty', 'Free kick penalty'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card')], max_length=191)),
                ('time', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_joined', core.models.GeneralCharField(max_length=191)),
                ('date_quited', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('type', core.models.GeneralCharField(choices=[('goal_keeper', 'Goal Keeper'), ('forward', 'Forward'), ('defender', 'Defender'), ('winger', 'Winger'), ('middle_defender', 'Middle Defender'), ('middle_attacker', 'Middle Attacker')], max_length=191)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Club')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('slug', core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True)),
                ('dob', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('nationality', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('height', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True)),
                ('position', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('nationality', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('height', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Referee',
                'verbose_name_plural': 'Referees',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='SiteSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', core.models.GeneralCharField(max_length=191)),
                ('content', core.models.GeneralCharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(default=None, max_length=191, null=True)),
                ('capable', models.PositiveIntegerField(default=None, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stadium',
                'verbose_name_plural': 'Stadiums',
            },
        ),
        migrations.AlterUniqueTogether(
            name='siteslug',
            unique_together={('slug', 'content')},
        ),
        migrations.AddField(
            model_name='membership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stadium'),
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(through='core.Membership', to='core.Player'),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stadium'),
        ),
    ]
