# Generated by Django 2.0.3 on 2018-07-01 11:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchaction',
            name='name',
            field=core.models.GeneralCharField(default=None, max_length=191, null=True, unique=True),
        ),
    ]
