# Generated by Django 2.0.3 on 2018-05-21 02:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('link', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('position', core.models.GeneralCharField(choices=[('index_1', 'Vị trí thứ nhất trang chủ'), ('index_2', 'Vị trí thứ 2 trang chủ')], max_length=191)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
