# Generated by Django 2.0.3 on 2018-07-02 03:41

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180701_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website',
            field=core.models.GeneralCharField(blank=True, default=None, max_length=191, null=True),
        ),
    ]
