# Generated by Django 2.0.3 on 2018-05-21 04:54

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_place',
            field=core.models.GeneralCharField(blank=True, choices=[('block_1', 'Vị trí trung tâm trang chủ'), ('block_2', 'Block 2 trang chủ')], max_length=191, null=True),
        ),
    ]
