# Generated by Django 2.0.3 on 2018-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_club_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='clubs',
            field=models.ManyToManyField(to='core.Club'),
        ),
        migrations.AddField(
            model_name='post',
            name='clubs',
            field=models.ManyToManyField(to='core.Club'),
        ),
        migrations.AddField(
            model_name='social',
            name='clubs',
            field=models.ManyToManyField(to='core.Club'),
        ),
    ]
