# Generated by Django 2.0.3 on 2018-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180703_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
