# Generated by Django 2.0.3 on 2018-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180810_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='background_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
