# Generated by Django 2.0.3 on 2018-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_club_background_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
