# Generated by Django 2.0.3 on 2018-08-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180813_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, to='core.Club'),
        ),
        migrations.AlterField(
            model_name='matchdetail',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, to='core.Club'),
        ),
        migrations.AlterField(
            model_name='social',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, to='core.Club'),
        ),
    ]
