# Generated by Django 2.0.3 on 2018-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180813_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='clubs',
            field=models.ManyToManyField(to='core.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clubs',
            field=models.ManyToManyField(to='core.Club'),
        ),
        migrations.AlterField(
            model_name='social',
            name='clubs',
            field=models.ManyToManyField(to='core.Club'),
        ),
    ]
