# Generated by Django 2.0.3 on 2018-08-14 03:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180814_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdetail',
            old_name='is_score',
            new_name='is_away_score',
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='in_match_part',
            field=core.models.GeneralCharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half'), ('hiep_phu1', 'Hiệp phụ 1'), ('hiep_phu2', 'Hiệp phụ 2'), ('penalty_time', 'Đá Penalty')], max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='is_home_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='more_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
