# Generated by Django 2.0.3 on 2018-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180814_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='attend_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
