# Generated by Django 2.0.3 on 2018-08-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_player_club_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='core.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='core.Club'),
        ),
        migrations.AlterField(
            model_name='social',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='core.Club'),
        ),
    ]
