# Generated by Django 2.0.3 on 2018-08-21 02:50

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180821_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=core.models.GeneralCharField(blank=True, default=None, max_length=191, null=True),
        ),
    ]
