# Generated by Django 2.0.3 on 2018-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_club_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
