# Generated by Django 2.0.3 on 2018-08-23 04:00

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180823_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=core.models.GeneralSlug(allow_unicode=True, blank=True, editable=False, max_length=191, null=True),
        ),
    ]
